const moviesData=[
{ id:Math.random() ,
  title:'Bohemian Rhapsody' ,
  description:'The story of the legendary British rock band Queen and lead singer Freddie Mercury,leading up to their famous performance at Live Aid (1985).' ,
  date:'2018' ,
  poster:'./moviePosters/bohemian_rhapsody.jpg' ,
  bg:'./movieBackgrounds/bohemian_bg.jpg',
  rate: 5,
},
{ id:Math.random() ,
  title:'Creed' ,
  description:'The former World Heavyweight Champion Rocky Balboa serves as a trainer to Adonis Johnson, the son of his late friend and former rival Apollo Creed.' ,
  date:'2015' ,
  poster:'./moviePosters/creed.jpg' ,
  bg:'./movieBackgrounds/creed_bg.jpg',
  rate: 4,
},
{ id:Math.random() ,
  title:'Dont Breath' ,
  description:'Hoping to walk away with a massive fortune, a trio of thieves break into the house of a blind man who isnt as helpless as he seems.' ,
  date:'2015' ,
  poster:'./moviePosters/dont_breath.jpg' ,
  bg:'./movieBackgrounds/dontbreath_bg.jpg',
  rate: 4,
},
{ id:Math.random() ,
  title:'Fast And Furious 5' ,
  description:'Dominic Toretto and his crew of street racers plan a massive heist to buy their freedom while in the sights of a powerful Brazilian drug lord and a dangerous federal agent.' ,
  date:'2011' ,
  poster:'./moviePosters/fast_and_furious.jpg' ,
  bg:'./movieBackgrounds/fastfive_bg.jpg',
  rate:4 ,
},
{ id:Math.random() ,
  title:'Free States Of Jhones' ,
  description:'A disillusioned Confederate army deserter returns to Mississippi and leads a militia of fellow deserters and women in an uprising against the corrupt local Confederate government.' ,
  date:'2016' ,
  poster:'./moviePosters/free_states_of_jhones.jpg' ,
  bg:'./movieBackgrounds/free_bg.jpg',
  rate:2 ,
},
{ id:Math.random() ,
  title:'Leon' ,
  description:'Mathilda, a 12-year-old girl, is reluctantly taken in by Léon, a professional assassin, after her family is murdered. An unusual relationship forms as she learns the assassins trade.' ,
  date:'1994' ,
  poster:'./moviePosters/leon.jpg' ,
  bg:'./movieBackgrounds/leon_bg.jpg',
  rate:5,
},
{ id:Math.random() ,
  title:'The Expendables' ,
  description:'A CIA operative hires a team of mercenaries to eliminate a Latin dictator and a renegade CIA agent.' ,
  date:'2010' ,
  poster:'./moviePosters/the_expendables.jpg' ,
  bg:'./movieBackgrounds/expendables_bg.jpg',
  rate:3,
},
{ id:Math.random() ,
  title:'The Grudge' ,
  description:'An American nurse living and working in Tokyo is exposed to a mysterious supernatural curse.' ,
  date:'2004' ,
  poster:'./moviePosters/the_grudge.jpg' ,
  bg:'./movieBackgrounds/grudge_bg.jpg',
  rate:4 ,
},
{ id:Math.random() ,
  title:'The Nun' ,
  description:'A priest with a haunted past and a novice on the threshold of her final vows are sent by the Vatican to investigate the death of a young nun in Romania.' ,
  date:'2018' ,
  poster:'./moviePosters/the_nun.jpg' ,
  bg:'./movieBackgrounds/thenun_bg.jpg',
  rate:3 ,
},
{ id:Math.random() ,
  title:'The Road' ,
  description:'In a dangerous post-apocalyptic world, an ailing father defends his son as they slowly travel to the sea.' ,
  date:'2009' ,
  poster:'./moviePosters/the_road.jpg' ,
  bg:'./movieBackgrounds/road_bg.jpg',
  rate:2 ,
}
];
export default moviesData;
