const moviesData=[
{ id:Math.random() ,
  title:'Bohemian Rhapsody' ,
  description:'The story of the legendary British rock band Queen and lead singer Freddie Mercury,leading up to their famous performance at Live Aid (1985).' ,
  date:'2018' ,
  poster:'./moviePosters/bohemian_rhapsody.jpg' ,
  bg:'./movieBackgrounds/bohemian_bg.jpg',
  rate: 5,
  trailer:"https://www.youtube.com/watch?v=mP0VHJYFOAU",
  fulldesc:"Singer Freddie Mercury, guitarist Brian May, drummer Roger Taylor and bass guitarist John Deacon take the music world by storm when they form the rock 'n' roll band Queen in 1970. Hit songs become instant classics. When Mercury's increasingly wild lifestyle starts to spiral out of control, Queen soon faces its greatest challenge yet – finding a way to keep the band together amid the success and excess.",
},
{ id:Math.random() ,
  title:'Creed' ,
  description:'The former World Heavyweight Champion Rocky Balboa serves as a trainer to Adonis Johnson, the son of his late friend and former rival Apollo Creed.' ,
  date:'2015' ,
  poster:'./moviePosters/creed.jpg' ,
  bg:'./movieBackgrounds/creed_bg.jpg',
  rate: 4,
  trailer:"https://www.youtube.com/watch?v=Uv554B7YHk4",
  fulldesc:"Adonis Johnson never knew his father, the famous world heavyweight champion Apollo Creed who died before his birth. However, he has boxing in his blood and decides to be trained by the best in his class. In Philadelphia, he tracks down Rocky Balboa, whom his father once faced, and asks him to become his coach. At first reluctant the former champion detects an unwavering strength in Adonis and ends up accepting ...",
},
{ id:Math.random() ,
  title:'Dont Breath' ,
  description:'Hoping to walk away with a massive fortune, a trio of thieves break into the house of a blind man who isnt as helpless as he seems.' ,
  date:'2015' ,
  poster:'./moviePosters/dont_breath.jpg' ,
  bg:'./movieBackgrounds/dontbreath_bg.jpg',
  rate: 4,
  trailer:"https://www.youtube.com/watch?v=76yBTNDB6vU",
  fulldesc:"To escape his mother’s violence and save his younger sister from a dead end existence, Rocky is ready for anything. With her friends Alex and Money, she has already committed a few burglaries, but nothing that earns them enough to finally leave Detroit. When the trio hear about a blind man who lives alone and keeps a small fortune in his home, they plan what they think is their final move. But their victim will turn out to be much more frightening, and above all much more dangerous than what they expected ...",
},
{ id:Math.random() ,
  title:'Fast And Furious 5' ,
  description:'Dominic Toretto and his crew of street racers plan a massive heist to buy their freedom while in the sights of a powerful Brazilian drug lord and a dangerous federal agent.' ,
  date:'2011' ,
  poster:'./moviePosters/fast_and_furious.jpg' ,
  bg:'./movieBackgrounds/fastfive_bg.jpg',
  rate:4 ,
  trailer:'https://www.youtube.com/watch?v=CYV-mTqlI_g',
  fulldesc:'Since Brian and Mia Toretto uprooted Dom from justice, they have had to cross many borders to escape the authorities. Retired in Rio, they are forced to mount one last blow to be cleared and regain their freedom. They form an elite team, bringing together the most knowledgeable pilots, aware that their only chance of being acquitted for good behavior requires a confrontation with the crooked businessman who wishes to see them dead. But he is not alone in their heels. Ruthless Federal Agent Luke Hobbs never missed his mark. Assigned to the hunt for the fugitives, he and his shock team develop a relentless assault device intended to capture them. Sifting through Brazil, Hobbs realizes how thin the line between the good and the bad is. He must then rely on his instinct to corner his prey and prevent another from flushing them out before him.',
},
{ id:Math.random() ,
  title:'Free States Of Jhones' ,
  description:'A disillusioned Confederate army deserter returns to Mississippi and leads a militia of fellow deserters and women in an uprising against the corrupt local Confederate government.' ,
  date:'2016' ,
  poster:'./moviePosters/free_states_of_jhones.jpg' ,
  bg:'./movieBackgrounds/free_bg.jpg',
  rate:2 ,
  trailer:'https://www.youtube.com/watch?v=3EMkxEKKSQI',
  fulldesc:'In the midst of the Civil War, Newton Knight, a courageous farmer from Mississippi, led a group of modest white peasants and slaves on the run to fight against the Confederate states. Forming a regiment of indomitable rebels, Knight and his men have the strategic advantage of knowing the terrain, even if their enemies are far more numerous and far better armed… Resolutely committed to injustice and human exploitation, the intrepid farmer founds the first state of free men where blacks and whites are equal.',
},
{ id:Math.random() ,
  title:'Leon' ,
  description:'Mathilda, a 12-year-old girl, is reluctantly taken in by Léon, a professional assassin, after her family is murdered. An unusual relationship forms as she learns the assassins trade.' ,
  date:'1994' ,
  poster:'./moviePosters/leon.jpg' ,
  bg:'./movieBackgrounds/leon_bg.jpg',
  rate:5,
  trailer:'https://www.youtube.com/watch?v=jawVxq1Iyl0',
  fulldesc:'A hired killer by the name of Leon takes under his wing Mathilda, a little girl of twelve, the only survivor of the massacre of her family. Soon Leon will make Mathilda a cleaner like him And Mathilda will be able to avenge her little brother',
},
{ id:Math.random() ,
  title:'The Expendables' ,
  description:'A CIA operative hires a team of mercenaries to eliminate a Latin dictator and a renegade CIA agent.' ,
  date:'2010' ,
  poster:'./moviePosters/the_expendables.jpg' ,
  bg:'./movieBackgrounds/expendables_bg.jpg',
  rate:3,
  trailer:'https://www.youtube.com/watch?v=8KtYRALe-xo',
  fulldesc:'An ensemble action film series about a group of elite mercenaries. The series pay tribute to the blockbuster action films of the 1980s and early 1990s, and stars an array of action veterans from those decades.',
},
{ id:Math.random() ,
  title:'The Grudge' ,
  description:'An American nurse living and working in Tokyo is exposed to a mysterious supernatural curse.' ,
  date:'2004' ,
  poster:'./moviePosters/the_grudge.jpg' ,
  bg:'./movieBackgrounds/grudge_bg.jpg',
  rate:4 ,
  trailer:'https://www.youtube.com/watch?v=pJFYq7g6pEk',
  fulldesc:'In what appears to be a peaceful Tokyo home hides one of the most dreadful plagues there is. Anyone who crosses the threshold of the house is immediately struck by a curse that will soon kill him in a feeling of unspeakable rage. As the number of victims increases, a young American, Karen, finds herself brutally confronted with the horror of this reality. For her, it is no longer time to ignore or flee, you have to understand to have a chance of surviving.',
},
{ id:Math.random() ,
  title:'The Nun' ,
  description:'A priest with a haunted past and a novice on the threshold of her final vows are sent by the Vatican to investigate the death of a young nun in Romania.' ,
  date:'2018' ,
  poster:'./moviePosters/the_nun.jpg' ,
  bg:'./movieBackgrounds/thenun_bg.jpg',
  rate:3 ,
  trailer:'https://www.youtube.com/watch?v=zwAM5UnGd2s',
  fulldesc:'When we learn of the suicide of a young nun in a Romanian abbey, there is total amazement in the Catholic Church. The Vatican immediately commissioned a priest with a troubled past and a novice to lead the investigation. Risking their lives, the two clergymen must face an evil force that shakes their faith and threatens to destroy their souls. Soon, the abbey is in the grip of a merciless struggle between the living and the damned ...',
},
{ id:Math.random() ,
  title:'The Road' ,
  description:'In a dangerous post-apocalyptic world, an ailing father defends his son as they slowly travel to the sea.' ,
  date:'2009' ,
  poster:'./moviePosters/the_road.jpg' ,
  bg:'./movieBackgrounds/road_bg.jpg',
  rate:2 ,
  trailer:'https://www.youtube.com/watch?v=bO8EqMsxOiU',
  fulldesc:'A father and his son walk alone through burned America. Nothing moves in the ravaged landscape save the ash on the wind and water. It is cold enough to crack stones, and, when the snow falls it is gray. The sky is dark. Their destination is the warmer south, although they dont know what, if anything, awaits them there.',
}
];
export default moviesData;
